#!/usr/bin/env python3
"""
patch_gups.py - make the GUPS hot-set relocation reachable and observable.

Replaces the earlier hand-written .diff, which was corrupt: unified diffs
depend on exact line numbers and context, and this one was written by reading
the file rather than generated by `git diff`.  Exact string replacement has no
such dependency, verifies every edit landed, and is idempotent.

WHAT AND WHY
------------
Stock gups-hotset-move.c relocates its hot set at tic>=150 -- 150 wall-clock
seconds.  Our runs end at ~35s when the worker threads exhaust their iteration
counts, so move_hotset1 never flips and the "hotset move" datasets contain no
relocation at all; they are behaviourally identical to gups_skewed.  Evidence:
results/gups_hotset_move_never_moved.txt.

This patch:
  1. GUPS_MOVE_AT_SEC makes the move time configurable (default 150 = stock).
  2. Logs the relocation timestamp on CLOCK_MONOTONIC -- the same clock the
     manager writes into timestamp_ns -- so the ground-truth event aligns to a
     CSV row exactly instead of being estimated.
  3. Logs the mmap base and per-thread geometry, so hot/cold ground truth
     ((addr - base) mod slice_bytes < hot_bytes) needs no guessing.

Usage:
    python3 patch_gups.py [path/to/gups-hotset-move.c]
    (default: ~/benchmarks/workloads/gups_hemem/gups-hotset-move.c)
"""
import os
import sys

DEFAULT = os.path.expanduser(
    "~/benchmarks/workloads/gups_hemem/gups-hotset-move.c")

MARKER = "LDOS_GROUNDTRUTH"   # idempotency check

# --- 1. helpers + globals, inserted just before timing_thread ---------------
OLD_HEAD = """bool stop = false;

static void *timing_thread()
{
  uint64_t tic = -1;
  bool printed1 = false;
  for (;;) {
    tic++;
    if (tic >= 150 && tic < 300) {
      if (!printed1) {
        move_hotset1 = true;
        fprintf(stderr, "moved hotset1\\n");
        printed1 = true;
      }
    }
    if (tic >= 250) {
      stop = true;
    }
    sleep(1);
  }
  return 0;
}"""

NEW_HEAD = """bool stop = false;

/* ---- LDOS instrumentation ---------------------------------------------- */
#include <time.h>

/* Relocation time in seconds.  Default 150 preserves stock behaviour; set
 * GUPS_MOVE_AT_SEC to something inside the run's actual duration or the move
 * never happens (which is what produced the original no-move datasets). */
static uint64_t ldos_move_at_sec(void)
{
  const char *e = getenv("GUPS_MOVE_AT_SEC");
  return (e != NULL) ? strtoull(e, NULL, 10) : 150;
}

/* CLOCK_MONOTONIC ns -- must match the manager's get_time_ns() so the logged
 * move timestamp lines up with timestamp_ns in the exported CSV. */
static uint64_t ldos_mono_ns(void)
{
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}

/* Set in main() once the region is mapped. */
void *ldos_region_base = NULL;
unsigned long ldos_region_size = 0;
unsigned long ldos_slice_bytes = 0;   /* per-thread region size */
unsigned long ldos_hot_bytes = 0;     /* per-thread hot-set size */
/* ------------------------------------------------------------------------ */

static void *timing_thread()
{
  uint64_t tic = -1;
  bool printed1 = false;
  uint64_t at = ldos_move_at_sec();
  for (;;) {
    tic++;
    if (tic >= at) {
      if (!printed1) {
        move_hotset1 = true;
        /* GROUND TRUTH -- everything needed to label pages hot/cold with no
         * reference to any measured access rate. */
        fprintf(stderr,
                "LDOS_GROUNDTRUTH move_ns=%llu region_base=%p region_size=%lu "
                "slice_bytes=%lu hot_bytes=%lu tic=%llu\\n",
                (unsigned long long)ldos_mono_ns(), ldos_region_base,
                ldos_region_size, ldos_slice_bytes, ldos_hot_bytes,
                (unsigned long long)tic);
        fflush(stderr);
        printed1 = true;
      }
    }
    if (tic >= at + 100) {
      stop = true;
    }
    sleep(1);
  }
  return 0;
}"""

# --- 2. record the mmap base ------------------------------------------------
OLD_BASE = ('  fprintf(stderr, "Region address: %p - %p\\t size: %ld\\n", '
            'p, (p + size), size);')
NEW_BASE = OLD_BASE + """
  ldos_region_base = p;
  ldos_region_size = size;"""

# --- 3. record + log the per-thread geometry -------------------------------
OLD_GEOM = """  hot_start = 0;
  hotsize = (tot_hot_size / threads) / elt_size;"""
NEW_GEOM = """  hot_start = 0;
  hotsize = (tot_hot_size / threads) / elt_size;
  ldos_slice_bytes = nelems * elt_size;
  ldos_hot_bytes = hotsize * elt_size;
  fprintf(stderr,
          "LDOS_GEOMETRY region_base=%p region_size=%lu slice_bytes=%lu "
          "hot_bytes=%lu threads=%d elt_size=%lu\\n",
          p, size, ldos_slice_bytes, ldos_hot_bytes, threads, elt_size);
  fflush(stderr);"""

EDITS = [("timing_thread + helpers", OLD_HEAD, NEW_HEAD),
         ("mmap base capture", OLD_BASE, NEW_BASE),
         ("per-thread geometry", OLD_GEOM, NEW_GEOM)]


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    if not os.path.exists(path):
        sys.exit(f"not found: {path}")

    src = open(path).read()
    if MARKER in src:
        print(f"already patched: {path}")
        return

    for name, old, new in EDITS:
        n = src.count(old)
        if n != 1:
            sys.exit(f"FAILED on '{name}': expected 1 match, found {n}.\n"
                     f"The upstream file differs from what this patcher "
                     f"expects; do not proceed -- an unpatched binary "
                     f"silently produces another no-move dataset.")
        src = src.replace(old, new)
        print(f"  applied: {name}")

    open(path + ".ldos-backup", "w").write(open(path).read())
    open(path, "w").write(src)
    print(f"patched {path}  (backup: {path}.ldos-backup)")


if __name__ == "__main__":
    main()
